spring:
  application:
    name: recipe-app
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true # I think it is default value
  docker:
    compose:
      lifecycle-management: start_only
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/recipe-app
    username: recipe-app
    password: recipe-app
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      console-available: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  mail:
    host: ${RECIPE_MAIL_HOST:smtp.gmail.com}
    port: ${RECIPE_MAIL_PORT:587}
    username: ${RECIPE_MAIL_USERNAME:}
    password: ${RECIPE_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

server:
  port: 8080

recipe:
  app-dir: ${user.home}/.recipe-app
  base-url: http://localhost:${server.port}